### ISSUE TITLE
what does this ? i can't get please explain?

### ISSUE THREAD

**Issue by hassaanhameed786** [oDqnger/Dice-Roll-Simulation#1]
https://github.com/oDqnger/Dice-Roll-Simulation/blob/a398a821c86c5c300eefaf8556cbfe811b74ef30/main.py#L28

**Comment by oDqnger** [comment]
Hi. Thanks for creating a issue for this repo. I apologise, but I do not understand the issue you wrote. I assume you’re trying get what line 28 means or what it does?

 If so, what you’re looking at here is something called list comprehension in Python. It is when you are allowed to make a completely new list by using something else (like a list or a string, in this case it’s the range function). For example, if you wanted to make a list with the first 200 elements of a list or if you wanted to make a list with first few even numbers, you could easily do this using a for loop. However, with list comprehensions you reduce it to just one line of code.

So what we’re doing here is we’re looping through all the dices (line 27) and we’re creating a new key for the dictionary where it stored the type of dice or dice number and the value of the key will be a list. Then what we do is we iterate through the amount of dice rolls and for each dice roll, we associate a random number between 1 and 6.

So the result would look something like this:

Input:
Number of dices = 4
Dice rolls = 3

Output:
Dice 1: [6, 3, 2]
Dice 2: [5, 2, 7]
Dice 3: [9, 6, 3]
Dice 4: [5, 2, 6]

I hope this helps. If there is something that you do not understand from what I wrote or if you think that what I wrote was wrong, please do bring it up. Thanks again and sorry for the late reply.

**Comment by hassaanhameed786** [comment]
yes ,I got it I was just wondering your profile so I open this code and start reading :) 👍

**Comment by oDqnger** [comment]
oh alright thank you :)
